// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srrqshemsftjirhuhtlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNycnFzaGVtc2Z0amlyaHVodGxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5NDMyNTAsImV4cCI6MjA3NzUxOTI1MH0.SOS4qynNjX_EEAzy_GWZBouxhDsGA3vvXAvqdsHDaa0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});